name: 'snowflake_dedup_identification'
version: '1.0.0'
config-version: 2

profile: 'snowflake_dedup_identification'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
